#!/usr/bin/env node
// Generate the native catalog from approved canonical JSON; --check detects drift.
import { readFileSync, writeFileSync } from "node:fs";
const root = new URL("../../", import.meta.url);
const data = JSON.parse(
  readFileSync(
    new URL("packages/www/src/lib/discovery/catalog.json", root),
    "utf8",
  ),
);
const target = new URL(
  "../morpheus/morpheus/MorpheusRuntime/Cloud/MorpheusDiscovery.swift",
  root,
);
const labels = {
  ship: "Ship",
  voodoo: "Island dream",
  harem: "Palace dream",
  waterfront: "Waterfront dream",
  carnival: "Carnival dream",
  ending: "Ending",
};
let output = String.raw`import Foundation

// Generated by morpheus-web/scripts/discovery/generate-swift.mjs from catalog.json.
nonisolated enum MorpheusDiscovery {
    static let catalogVersion = 2
    static let mapDigest = "DIGEST"
    struct Count: Equatable, Sendable {
        let discovered: Int
        let total: Int
        var percent: Double { total == 0 ? 0 : Double(discovered * 1_000 / total) / 10 }
        var percentText: String { percent.formatted(.number.precision(.fractionLength(0...1))) + "%" }
    }
    struct Unit: Equatable, Sendable {
        let id: String
        let sectionID: String
        let sceneIDs: [Int]
        let assets: [String]
    }
    struct Section: Equatable, Sendable {
        let id: String
        let label: String
        var groups: [[Int]] { units.filter { $0.sectionID == id }.map(\.sceneIDs) }
    }
    static func section(containing sceneID: Int) -> Section? {
        let conditionalUnitID = conditionalObservations.first { $0.sceneID == sceneID }?.unitID
        let id = units.first { $0.sceneIDs.contains(sceneID) || $0.id == conditionalUnitID }?.sectionID
        return sections.first { $0.id == id }
    }
    static func count(_ visits: Set<Int>, observedDiscoveryIDs: Set<String> = [], sectionID: String? = nil) -> Count {
        let selected = units.filter { sectionID == nil || $0.sectionID == sectionID }
        return Count(discovered: selected.filter {
            observedDiscoveryIDs.contains($0.id) || !$0.sceneIDs.allSatisfy { !visits.contains($0) }
        }.count, total: selected.count)
    }
    static func isCompleted(_ visits: Set<Int>) -> Bool {
        !visits.isDisjoint(with: [895051, 895052, 895053, 895054, 895055, 895056, 895057, 895058, 895065, 895066])
    }
    static let validUnitIDs = Set(units.map(\.id))
    static func observedIDs(sceneID: Int, visibleAssetPaths: [String] = []) -> Set<String> {
        if let unit = units.first(where: { $0.sceneIDs.contains(sceneID) }) {
            return visibleAssetPaths.contains(where: { unit.assets.contains($0) }) ? [unit.id] : []
        }
        return Set(conditionalObservations.filter {
            $0.sceneID == sceneID && visibleAssetPaths.contains($0.asset)
        }.map(\.unitID))
    }
    private static let conditionalObservations: [(sceneID: Int, asset: String, unitID: String)] = [
CONDITIONS
    ]
    static let sections: [Section] = [
SECTIONS
    ]
    static let units: [Unit] = [
UNITS
    ]
}
`;
output = output
  .replace("DIGEST", data.mapDigest)
  .replace(
    "SECTIONS",
    Object.entries(labels)
      .map(([id, label]) => `        Section(id: "${id}", label: "${label}")`)
      .join(",\n"),
  )
  .replace(
    "UNITS",
    data.units
      .map(
        (u) =>
          `        Unit(id: "${u.id}", sectionID: "${u.section}", sceneIDs: [${u.sceneIds.join(", ")}], assets: [${u.assets.map(JSON.stringify).join(", ")}])`,
      )
      .join(",\n"),
  )
  .replace(
    "CONDITIONS",
    data.units
      .flatMap((u) =>
        (u.conditionalObservations ?? []).map(
          (c) => `        (${c.sceneId}, "${c.visibleAsset}", "${u.id}")`,
        ),
      )
      .join(",\n"),
  );
if (process.argv.includes("--check")) {
  if (readFileSync(target, "utf8") !== output)
    throw new Error("Swift discovery catalog differs; run generator");
} else writeFileSync(target, output);
